### ISSUE TITLE
Markdown 语法练习

### ISSUE THREAD

**Issue by xiethon** [xiethon/blog#1]
# HEADERS
-------------------------------------------
# This is an H1 tag
###### Thist is an H6 tag

--------------------------------------------
# EMPHASIS
*This text will be italic*  
_This will also be italic_  

   
**This text will be bold**  
__This will also be bold__  
*You **can** combine them*    

--------------------------------------------------
# BLOCKQUOTES
As Grace Hopper said:  
> **I've always been more interested**  
> **in the future than in the past.**

------------------------------------------
# Unordered
- Item 1
- Ttem 2
	1. Item 2a
	2. Item ab
-----------------------------------------
# Link

[GitHub](www.github/xiethon)

---------------------------------------------

\*literal asterisks\*

--------------------------------------------
# EMOJI

GitHub supports emoji!  
:+1: :sparkles: :camel: :tada: :rocket: :metal: :octocat:

-----------------------------------
# Task List

- [x] this is a complete item
- [ ] this is an incomplete item
- [x] @memtion,#refs,[links](),

----------------------------------

	code test
	int a = 10;
